---
name: build frontend site

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    name: render the html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: invoke neuron docker container
        run: |
          docker run --rm \
                  -v $(pwd)/src:/data \
                  -v $(pwd)/docs/:/output \
                  sw00/neuron-zk \
                  rib -o /output

      - name: commit the rendered files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Publish changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

